name: "Update Angular Action"
on: # when the action should run. Can also be a CRON or in response to external events. see https://git.io/JeBz1
  schedule:
    - cron: '30 5 * * 1,3,5'

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies # the magic happens here !
        uses: fast-facts/ng-update@v1
        with:
          base-branch: main
          project-path: ./crud-angular
          repo-token: ${{ secrets.GITHUB_TOKEN }}
